### ISSUE TITLE
error 404 Not Found: gatsby-transformer-contentful-richtext@latest

### ISSUE THREAD

**Issue by imshuffling** [contentful/gatsby-transformer-contentful-richtext#4]
Error running `npm install --save gatsby-transformer-contentful-richtext`

Tried clearing npm cache as I thought it could be this, any ideas?

**Comment by loudmouth** [comment]
Hi @imshuffling while we did just merge our first PRs this morning, we have not had time to publish to `npm`.

Actually, we will be continuing work on the plugin in a different repo: the [rich-text](https://github.com/contentful/rich-text) mono-repo. We have a [PR open there](https://github.com/contentful/rich-text/pull/26), but still have one test to fix before we can merge and publish.

Thanks for your patience.

**Comment by imshuffling** [comment]
OK Thanks @loudmouth, eager to try this plugin out. :)
